In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Types and Shape

In [3]:
#convert list to tensor

twoD_tensor = torch.tensor([[21,3,56], [99,85,11], [1, 4,9]])
print(twoD_tensor)

tensor([[21,  3, 56],
        [99, 85, 11],
        [ 1,  4,  9]])


In [6]:
print("The dimension is ", twoD_tensor.ndimension())
print("The shape is ", twoD_tensor.shape)
print("The shape is ", twoD_tensor.size())
print("The number of elements is ",twoD_tensor.numel())

The dimension is  2
The shape is  torch.Size([3, 3])
The shape is  torch.Size([3, 3])
The number of elements is  9


In [7]:
#convert tensor to numpy array : convert numpy array to twoD_tensor

twoD_numpy = twoD_tensor.numpy()
print("Tensor --> Numpy Array: ")
print("The numpy array: ",twoD_numpy)
print("Type after converting: ", twoD_numpy.dtype)

new_twoD_tensor = torch.from_numpy(twoD_numpy)
print("\n Numpy Array-->Tensor: ")
print("Tensor: ",new_twoD_tensor)
print("Type after converting: ", new_twoD_tensor.dtype)

Tensor --> Numpy Array: 
The numpy array:  [[21  3 56]
 [99 85 11]
 [ 1  4  9]]
Type after converting:  int64

 Numpy Array-->Tensor: 
Tensor:  tensor([[21,  3, 56],
        [99, 85, 11],
        [ 1,  4,  9]])
Type after converting:  torch.int64


In [8]:
#Panda to Tensor

df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})

print("Pandas Dataframe to numpy: ", df.values)
print("Type before converting: ",df.values.dtype)

print("\n")

new_tensor = torch.from_numpy(df.values)
print("Tensor after converting: ", new_tensor)
print('Type after converting: ',new_tensor.dtype)

Pandas Dataframe to numpy:  [[1 4]
 [2 5]
 [3 6]]
Type before converting:  int64


Tensor after converting:  tensor([[1, 4],
        [2, 5],
        [3, 6]])
Type after converting:  torch.int64


## Practice

In [9]:
df = pd.DataFrame({'A' : [11,22,33], 'B' : [55,66,77]})

convered_tensor = torch.tensor(df.values)
print("Tensors: ",convered_tensor)

Tensors:  tensor([[11, 55],
        [22, 66],
        [33, 77]])


## Indexing and Slicing

In [10]:
# indexing

tensor_example = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print("Value on 2nd row and 3rd column: ", tensor_example[1,2])

Value on 2nd row and 3rd column:  tensor(6)


In [11]:
tensor_example[0][0]

tensor(1)

In [12]:
#Slicing

tensor_example = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print("The value on 1st row two colums: ", tensor_example[0, 0:2])
print("The value on 1st row two colums: ", tensor_example[0] [0:2])

The value on 1st row two colums:  tensor([1, 2])
The value on 1st row two colums:  tensor([1, 2])


In [17]:
tensor_example = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
sliced_tensor = tensor_example[1:3]

print("Result is: ", sliced_tensor)
print("Dimension: ", sliced_tensor.ndimension())

print('===============================================')

print('Result after slice_tensor[1]: ',sliced_tensor[1])
print('Dimension after sliced_tensor[1]: ',sliced_tensor[1].ndimension())

print('================================================')

print('Result: ', tensor_example[1:3][1])
print('Dimension: ',tensor_example[1:3][1].ndimension())

Result is:  tensor([[4, 5, 6],
        [7, 8, 9]])
Dimension:  2
Result after slice_tensor[1]:  tensor([7, 8, 9])
Dimension after sliced_tensor[1]:  1
Result:  tensor([7, 8, 9])
Dimension:  1


In [22]:
tensor_example = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print('The values from 3rd column last two rows: ', tensor_example[1:3,2])

The values from 3rd column last two rows:  tensor([6, 9])


## Practice

In [34]:
#Use slice and index

tensor_ques = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print('Value on third row 2nd column: ', tensor_ques[2,1])
print('Value on second column and first two rows: ', tensor_ques[0:2,1])

tensor_ques[0:2,1] = 0
print('The result: ',tensor_ques)

Value on third row 2nd column:  tensor(8)
Value on second column and first two rows:  tensor([2, 5])
The result:  tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 8, 9]])


<h2 id="Tensor_Op">Tensor Operations</h2> 

<h3>Tensor Addition</h3>

In [35]:
#addition

x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[9,8],[5,7]])

z= x+y
print('Addition: ',z)

Addition:  tensor([[10, 10],
        [ 8, 11]])


In [38]:
#multiplication

two_x = 2 * x
print('Multiplication: ',two_x)

Multiplication:  tensor([[2, 4],
        [6, 8]])


In [40]:
print("The result of x and y: \n ", x*y)

The result of x and y: 
  tensor([[ 9, 16],
        [15, 28]])


In [43]:
A = torch.tensor([[2, 3, 1], [1, 0, 4]])
B = torch.tensor([[1, 2], [3, 4], [-1, 1]])
print('The result of A * B : \n ',torch.mm(A,B))

The result of A * B : 
  tensor([[10, 17],
        [-3,  6]])


In [44]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print(X_times_Y)

tensor([[2, 0],
        [0, 2]])
